"""empty message

Revision ID: 0858b59a3d69
Revises: a043554d9595
Create Date: 2024-09-06 19:11:36.089372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0858b59a3d69'
down_revision = 'a043554d9595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('passes', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_matches')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('home_team',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('away_team',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('home_team_result',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('away_team_result',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('away_team_result',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('home_team_result',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('away_team',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('home_team',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_table('users_matches',
    sa.Column('goals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shots', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shots_on_target', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fouls', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('yellow_cards', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('red_cards', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='users_matches_match_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_matches_user_id_fkey')
    )
    op.drop_table('user_match')
    # ### end Alembic commands ###
