"""empty message

Revision ID: c729299704fe
Revises: f44feada42e7
Create Date: 2024-09-06 19:21:36.100916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c729299704fe'
down_revision = 'f44feada42e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('passes', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_matches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_on_target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fouls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yellow_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('red_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='users_matches_match_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_matches_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_matches_pkey')
    )
    op.drop_table('user_match')
    # ### end Alembic commands ###
